services:
  db:
    image: ghcr.io/jmarthy7/hogwarts_backend_991:latest
    container_name: MySQL_jmb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "aaee_jmb"
      MYSQL_PASSWORD: "1234"
    ports:
      - "6666:3306"
